version: "3.5"

services:
  plausible_mail:
    image: bytemark/smtp
    container_name: plausible_mail
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    container_name: plausible_db
    restart: always
    volumes:
      - ${PATH_DATAS}/plausible/postgresql:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Paris
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      xenetis-network:

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    container_name: plausible_events_db
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${PATH_DATAS}/plausible/clickhouse:/var/lib/clickhouse
      - ./config/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./config/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      xenetis-network:

  plausible:
    image: plausible/analytics:latest
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
#      - plausible_mail
    environment:
      - TZ=Europe/Paris
    ports:
      - "8010:8000"
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
