version: "3.5"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${PATH_CONFIG}/sonarr:/config
      - ${PATH_DATAS}/series:/tv #optional
      - ${PATH_DATAS}/downloads:/downloads #optional
    ports:
      - "8012:8989"
    restart: unless-stopped
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
