version: "3.5"

services:
  privatebin:
    hostname: privatebin
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine:latest
    read_only: true
    ports:
      - "8008:8080"
    volumes:
      - ${PATH_DATAS}/privatebin:/srv/data # volume for persisted data pastes
      - ./config/conf.php:/srv/cfg/conf.php:ro # volume for custom privatebin config; please place the config.php file here
      #- ./config/nginx.conf:/etc/nginx/nginx.conf:ro # optional; custom nginx container config to increase file upload size
      #- ./config/php.ini:/etc/php81/conf.d/00-docker.ini:ro # optional; custom php container config to increase file upload size
    restart: unless-stopped
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
