version: "3.5"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${PATH_DATAS}/heimdall:/config
    ports:
      - 8001:80
    restart: always
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
