version: "3.5"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=1001
      - PLEX_GID=998
      - TZ=Enrope/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_URL]
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - ${PATH_CONFIG}/plex:/config
      - ${PATH_DATAS}/plex/temp:/transcode
      - ${PATH_DATAS}/plex/medias:/data
    networks:
      xenetis-network:

networks:
  xenetis-network:
    external:
      name: xenetis-network
