version: "3.5"

services:
  gitlab-ee:
    container_name: gitlab-ee
    image: 'gitlab/gitlab-ee:latest'
    ports:
      - "8009:80"
      #- "443:443"
      - "2223:22"
    environment:
      - TZ=Europe/Paris
    hostname: ${GITLAB_DOMAIN}
    volumes:
      - '${PATH_CONFIG}/gitlab-ee:/etc/gitlab'
      - '${PATH_DATAS}/gitlab-ee/logs:/var/log/gitlab'
      - '${PATH_DATAS}/gitlab-ee/data:/var/opt/gitlab'
    restart: unless-stopped
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
