version: "3.5"

services:
  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: always
    environment:
      - TZ=Europe/Paris
    ports:
      - 8118:8118
      - 9050:9050
    volumes:
      - "${PATH_CONFIG}/torproxy:/etc/tor"
      - "${PATH_DATAS}/torproxy:/var/lib/tor"
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
