version: '3.5'

services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: "portainer-agent"
    environment:
      AGENT_SECRET: ${PORTAINER_AGENT_SECRET}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9002:9001"
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
