version: "3.5"

services:
  dozzle:
    container_name: dozzle2
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8003:8080"
    environment:
      TZ: Europe/Paris
      DOZZLE_LEVEL: trace
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
