version: "3.5"

services:
  

  matomo:
    container_name: "matomo"
    image: 'matomo:4.10.1-apache'
    volumes:
      - '${PATH_DATAS}/matomo/data:/var/www/html'
    env_file:
      - ../global.env
      - .env
    environment:
      TZ: Europe/Paris
      MATOMO_DATABASE_HOST: 'matomo-db'
      MATOMO_DATABASE_ADAPTER: 'mysql'
      MATOMO_DATABASE_TABLES_PREFIX: 'matomo_'
      MATOMO_DATABASE_USERNAME: '${MATOMO_DB_USERNAME}'
      MATOMO_DATABASE_PASSWORD: '${MATOMO_DB_PASSWORD}'
      MATOMO_DATABASE_DBNAME: '${MATOMO_DB_DATABASE}'
    networks:
      xenetis-network:
    depends_on:
      - matomo-db

  matomo-db:
    container_name: "matomo-db"
    image: 'mariadb:10.5'
    environment:
      TZ: Europe/Paris
      MARIADB_ROOT_PASSWORD: '${MATOMO_DB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MATOMO_DB_DATABASE}'
      MARIADB_USER: '${MATOMO_DB_USERNAME}'
      MARIADB_PASSWORD: '${MATOMO_DB_PASSWORD}'
    volumes:
      - '${PATH_DATAS}/matomo/mysql:/var/lib/mysql'
    networks:
      xenetis-network:
    command: mysqld ${MARIADB_OPTS}

