version: "3.5"

services:

  matomo:
    container_name: "matomo"
    image: 'matomo:4.10.1-apache'
    volumes:
      - '${PATH_DATAS}/matomo/data:/var/www/html'
    environment:
      TZ: Europe/Paris
      MATOMO_DATABASE_HOST: 'matomo-db'
      MATOMO_DATABASE_ADAPTER: 'mysql'
      MATOMO_DATABASE_TABLES_PREFIX: 'matomo_'
      MATOMO_DATABASE_USERNAME: '${MARIADB_USER}'
      MATOMO_DATABASE_PASSWORD: '${MARIADB_PASSWORD}'
      MATOMO_DATABASE_DBNAME: '${MARIADB_DATABASE}'
    networks:
      xenetis-network:
    depends_on:
      - matomo-db

  matomo-db:
    container_name: "matomo-db"
    image: 'mariadb:10.5'
    environment:
      TZ: Europe/Paris
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MARIADB_DATABASE}'
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
    volumes:
      - "${PATH_DATAS}/matomo/mysql: /var/lib/mysql"
    networks:
      xenetis-network:
    command: mysqld ${MARIADB_OPTS}

networks:
  xenetis-network:
    external:
      name: xenetis-network
