version: "3.5"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${PATH_DATAS}/uptimekuma:/app/data
    ports:
      - "8015:3001"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    networks:
      xenetis-network:

networks:
  xenetis-network:
    name: xenetis-network
